name: CD
on:
  release:
    types:
      - published
env:
  java_version: 11
  java_distribution: zulu
  flutter_version: 3.10.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.java_distribution }}
          java-version: ${{ env.java_version }}
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN
        env:
          BACKEND_ORIGIN: ${{ secrets.BACKEND_ORIGIN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g firebase-tools
      - run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app $FIREBASE_APP --token $FIREBASE_TOKEN
        env:
          FIREBASE_APP: ${{ secrets.FIREBASE_APP }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
