name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  java_version: 11
  java_distribution: zulu
  flutter_version: 3.7.0
jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      BACKEND_ORIGIN: https://example.com
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.java_distribution }}
          java-version: ${{ env.java_version }}
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
      - run: flutter test --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN
      - run: xcrun xctrace list devices
      - run: xcrun simctl boot "iPhone 13"
      - run: flutter test --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN integration_test
