name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
env:
  java_version: '12.x'
  flutter_version: '2.0.2'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      BACKEND_ORIGIN: https://example.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
      - run: flutter test --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN
  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      BACKEND_ORIGIN: ${{ secrets.BACKEND_ORIGIN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN
      - run: flutter build ios --dart-define=BACKEND_ORIGIN=$BACKEND_ORIGIN --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/
      - uses: actions/upload-artifact@v2
        with:
          name: iphoneos
          path: build/ios/iphoneos/
  deploy-production:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: echo TODO
